(function(root) {
  'use strict';
  // Единый каталог исходных SVG и названий снаряжения из демопарсера.
  const files = ["ak47.svg","ammobox.svg","ammobox_threepack.svg","armor.svg","armor_helmet.svg","assaultsuit.svg","assaultsuit_helmet_only.svg","aug.svg","awp.svg","bayonet.svg","bizon.svg","c4.svg","clothing_hands.svg","customplayer.svg","cz75a.svg","deagle.svg","decoy.svg","defuser.svg","disconnect.svg","dronegun.svg","elite.svg","famas.svg","firebomb.svg","fiveseven.svg","flair0.svg","flashbang.svg","flashbang_assist.svg","g3sg1.svg","galilar.svg","glock.svg","grenadepack.svg","grenadepack2.svg","healthshot.svg","heavy_armor.svg","hegrenade.svg","helmet.svg","hkp2000.svg","incgrenade.svg","inferno.svg","kevlar.svg","knife.svg","knifegg.svg","knife_bowie.svg","knife_butterfly.svg","knife_canis.svg","knife_cord.svg","knife_css.svg","knife_falchion.svg","knife_flip.svg","knife_gut.svg","knife_gypsy_jackknife.svg","knife_karambit.svg","knife_kukri.svg","knife_m9_bayonet.svg","knife_outdoor.svg","knife_push.svg","knife_skeleton.svg","knife_stiletto.svg","knife_survival_bowie.svg","knife_t.svg","knife_tactical.svg","knife_twinblade.svg","knife_ursus.svg","knife_widowmaker.svg","m249.svg","m4a1.svg","m4a1_silencer.svg","m4a1_silencer_off.svg","mac10.svg","mag7.svg","melee.svg","molotov.svg","movelinear.svg","mp5sd.svg","mp7.svg","mp9.svg","negev.svg","nova.svg","p2000.svg","p250.svg","p90.svg","planted_c4.svg","prop_exploding_barrel.svg","revolver.svg","sawedoff.svg","scar20.svg","sg556.svg","smokegrenade.svg","spray0.svg","ssg08.svg","stomp_damage.svg","taser.svg","tec9.svg","trigger_hurt.svg","ump45.svg","usp_silencer.svg","usp_silencer_off.svg","world.svg","worldent.svg","xm1014.svg"];
  const normalize = value => String(value || '').toLowerCase().replace(/^weapon_/, '').replace(/[^a-z0-9]/g, '');
  const catalog = new Map(files.map(file => [normalize(file.slice(0, -4)), file]));
  const aliases = {"cz75auto":"cz75a","m4a4":"m4a1","m4a1s":"m4a1_silencer","usps":"usp_silencer","usp":"usp_silencer","glock18":"glock","galil":"galilar","galilar":"galilar","sg553":"sg556","deserteagle":"deagle","dualberettas":"elite","fiveseven":"fiveseven","p2000":"hkp2000","ppbizon":"bizon","r8revolver":"revolver","zeusx27":"taser","highexplosivegrenade":"hegrenade","hegrenade":"hegrenade","incendiarygrenade":"incgrenade","decoygrenade":"decoy","c4explosive":"c4","butterflyknife":"knife_butterfly","m9bayonet":"knife_m9_bayonet","talonknife":"knife_widowmaker","karambit":"knife_karambit","stilettoknife":"knife_stiletto","bowieknife":"knife_survival_bowie","classicknife":"knife_css","falchionknife":"knife_falchion","flipknife":"knife_flip","gutknife":"knife_gut","huntsmanknife":"knife_tactical","kukriknife":"knife_kukri","navajaknife":"knife_gypsy_jackknife","nomadknife":"knife_outdoor","paracordknife":"knife_cord","shadowdaggers":"knife_push","skeletonknife":"knife_skeleton","survivalknife":"knife_canis","ursusknife":"knife_ursus","defusekit":"defuser","kevlarvest":"kevlar","kevlarhelmet":"armor_helmet"};
  function asset(name) {
    const key = normalize(name);
    return aliases[key] ? aliases[key] + '.svg' : catalog.get(key) || null;
  }
  const api = { asset };
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.CSEquipment = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
